//! Shared spawn plumbing used by both the CLI worker path (`main.rs
//! run_spawn`) and the in-app standalone spawn (`app.rs SpawnFormConfirm`):
//! isolated worktree creation, repo-slug detection, tilde expansion, and the
//! interactive tmux+PTY launch sequence shared by both spawn-modal kinds.

use std::sync::Arc;

use ninox_core::{events::Engine, pty, tmux, Event, Session, SessionStatus};

/// The per-kind differences between the spawn-modal launch paths
/// (standalone vs orchestrator). Everything else — env resolution,
/// PATH-prepend launch command, tmux session creation, pid lookup,
/// session persistence, and PTY streaming — is identical and lives in
/// [`spawn_interactive_session`].
pub struct InteractiveSpawnParams {
    /// Session id; also used as the tmux session name.
    pub session_id:      String,
    pub name:            String,
    /// Directory the agent starts in (isolated worktree for standalone,
    /// per-orchestrator subdirectory for orchestrators). Recorded as the
    /// session's `workspace_path`.
    pub workspace:       String,
    /// GitHub `owner/repo` slug ("" when unknown / not applicable).
    pub repo:            String,
    pub orchestrator_id: Option<String>,
    pub agent:           ninox_core::config::AgentConfig,
    /// Resolved interactive launch command (registry-resolved by the
    /// caller: `AppConfig::registry().interactive_cmd(&agent)`). Kept
    /// separate from `agent` so this module needs no registry access;
    /// `agent` remains for session-record stamping (agent_type/model).
    pub base_cmd:        String,
    /// Brain catalogue path, exported as `NINOX_BRAIN` for both kinds.
    pub catalogue_path:  String,
    /// Extra env pairs beyond the shared NINOX_BIN/NINOX_CONFIG/NINOX_BRAIN
    /// (e.g. NINOX_ORCHESTRATOR_ID + caller-type vars for orchestrators).
    pub extra_env:       Vec<(String, String)>,
    pub started_at:      i64,
    /// UUID for `--session-id`/`--resume` (see `ninox_core::harness::new_claude_session_id`).
    /// Generated by the caller — this module never generates one itself,
    /// so `Re-file` (Task 8) can mint a fresh id while Resume (Task 10)
    /// reuses the session's existing one.
    pub claude_session_id: String,
    /// Status to set if `tmux::create_session` fails. `Terminated` for a
    /// fresh spawn or Re-file (nothing worth preserving); `Interrupted`
    /// for Resume (keep it retryable — see the design spec's Error
    /// Handling section).
    pub failure_status:  ninox_core::SessionStatus,
    /// One-line task summary carried over from the session being
    /// respawned (Re-file/Resume); `None` for a fresh spawn, which has no
    /// prior summary to preserve.
    pub summary:         Option<String>,
}

/// Launch an interactive agent session inside tmux and start PTY streaming.
///
/// On success, returns the tmux attach argv for the new session so the
/// caller can emit `Message::ClientAttach` and render it immediately at the
/// right size (the attached-client flow sizes the PTY to the real panel).
/// On tmux failure (e.g. the workspace path is bad) the session is marked
/// with the caller-supplied `p.failure_status` in the store (`Terminated`
/// for a fresh spawn or Re-file, `Interrupted` for Resume — see
/// `InteractiveSpawnParams::failure_status`), a `SessionUpdated` event is
/// emitted so the UI reflects the new status instead of a session stuck in
/// Working forever, and `None` is returned.
pub async fn spawn_interactive_session(
    engine: Arc<Engine>,
    p: InteractiveSpawnParams,
) -> Option<Vec<String>> {
    let sid = p.session_id;

    let ninox_bin = std::env::current_exe()
        .ok()
        .and_then(|x| x.to_str().map(str::to_string))
        .unwrap_or_else(|| "ninox".to_string());
    let ninox_config = ninox_core::config::AppConfig::config_path()
        .to_string_lossy()
        .to_string();
    // Session metadata dir — must be set for both Orchestrator and Standalone
    // kinds, mirroring the CLI worker path (`main.rs run_spawn`). Without
    // these, the gh/git wrapper scripts (`ninox_core::hooks`) have nowhere to
    // record PR/branch metadata for app-spawned sessions, and the usage
    // poller has no session id to attribute cost/token ingestion to.
    let sessions_dir = ninox_core::config::AppConfig::sessions_dir();
    std::fs::create_dir_all(&sessions_dir).ok();
    let sessions_dir_str = sessions_dir.to_string_lossy().to_string();

    let env = interactive_env_vars(
        &ninox_bin, &ninox_config, &p.catalogue_path, &sid, &sessions_dir_str, &p.extra_env,
    );

    // Prepend ninox bin dir inside the shell command so the `ninox` shim
    // (which points to the current binary) is found first — even after
    // login-shell rc files reorder PATH.
    let ninox_bin_dir = ninox_core::config::AppConfig::ninox_bin_dir();
    let ninox_bin_dir_str = ninox_bin_dir.display().to_string().replace('\'', "'\\''");
    let base_cmd = p.base_cmd;
    let launch_cmd = format!("export PATH='{ninox_bin_dir_str}':\"$PATH\"; {base_cmd}");

    if let Err(e) = tmux::create_session(&sid, &p.workspace, &launch_cmd, &env).await {
        tracing::error!("tmux create failed for {sid}: {e}");
        // Surface the failure: without this the optimistically inserted
        // session would sit in Working forever.
        if let Ok(Some(mut s)) = engine.store.get_session(&sid) {
            s.status = p.failure_status;
            let _ = engine.store.upsert_session(&s);
            engine.emit(Event::SessionUpdated(s));
        }
        return None;
    }

    tokio::time::sleep(tokio::time::Duration::from_millis(300)).await;

    let pid = tmux::list_sessions()
        .await
        .ok()
        .and_then(|ss| ss.into_iter().find(|s| s.id == sid))
        .and_then(|s| s.pid);

    let updated = Session {
        id:              sid.clone(),
        orchestrator_id: p.orchestrator_id,
        name:            p.name,
        repo:            p.repo,
        status:          SessionStatus::Working,
        agent_type:      p.agent.harness.clone(),
        cost_usd:        0.0,
        started_at:      p.started_at,
        pr_number:       None,
        pr_id:           None,
        workspace_path:  Some(p.workspace),
        pid,
        model:           p.agent.model.clone(),
        context_tokens:  None,
        catalogue_path:  (!p.catalogue_path.is_empty()).then(|| p.catalogue_path.clone()),
        context_used_pct: None, context_total_tokens: None, context_window_size: None,
        claude_session_id: Some(p.claude_session_id),
        summary:         p.summary,
        terminal_at:     None,
    };
    let _ = engine.store.upsert_session(&updated);

    if let Err(e) = pty::start_streaming(engine.clone(), sid.clone(), &sid).await {
        tracing::error!("pty setup failed for {sid}: {e}");
    }

    engine.emit(Event::SessionUpdated(updated));

    // Hidden tmux client attach argv — mirrors NavigateSession's attach flow.
    Some(tmux::attach_args(&sid).await)
}

/// The tmux env for an app-spawned interactive session (Orchestrator or
/// Standalone): the shared NINOX_BIN/NINOX_CONFIG/NINOX_BRAIN vars, session
/// metadata attribution (`NINOX_SESSION`/`NINOX_DATA_DIR` — consumed by
/// the gh/git wrapper scripts in `ninox_core::hooks` and by the usage
/// poller's cost/token ingestion), plus any kind-specific extra vars.
///
/// Factored out from [`spawn_interactive_session`] for unit testing: this is
/// the fix for the gap where app-spawned sessions never set the session
/// attribution vars (only the CLI worker path in `main.rs::run_spawn` did),
/// making PR/branch metadata capture and cost attribution silently
/// invisible for orchestrators and standalone spawns.
fn interactive_env_vars<'a>(
    ninox_bin:      &'a str,
    ninox_config:   &'a str,
    catalogue_path: &'a str,
    session_id:     &'a str,
    sessions_dir:   &'a str,
    extra_env:      &'a [(String, String)],
) -> Vec<(&'a str, &'a str)> {
    let mut env: Vec<(&str, &str)> = vec![
        ("NINOX_BIN",      ninox_bin),
        ("NINOX_CONFIG",   ninox_config),
        ("NINOX_BRAIN",    catalogue_path),
        ("NINOX_SESSION",  session_id),
        ("NINOX_DATA_DIR", sessions_dir),
    ];
    for (k, v) in extra_env {
        env.push((k.as_str(), v.as_str()));
    }
    env
}

/// Expand a leading `~` or `~/` in a user-supplied path to the home directory.
/// Returns the input unchanged when it doesn't start with `~` (or when the
/// home directory can't be resolved).
pub fn expand_tilde(path: &str) -> String {
    if path == "~" {
        if let Some(home) = dirs::home_dir() {
            return home.to_string_lossy().to_string();
        }
    } else if let Some(rest) = path.strip_prefix("~/") {
        if let Some(home) = dirs::home_dir() {
            return home.join(rest).to_string_lossy().to_string();
        }
    }
    path.to_string()
}

/// Read `git remote get-url origin` from the workspace and parse it as a
/// GitHub slug (`owner/repo`). Returns `None` if git fails or the URL is not
/// a recognisable GitHub remote.
pub fn repo_from_workspace(workspace: &str) -> Option<String> {
    let output = std::process::Command::new("git")
        .args(["-C", workspace, "remote", "get-url", "origin"])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let url = String::from_utf8_lossy(&output.stdout).trim().to_string();
    ninox_core::github::split_repo(&url).map(|(o, r)| format!("{o}/{r}"))
}

/// Create an isolated git worktree for a session at
/// `{repo}/.claude/worktrees/{session_id}` on a new branch `{session_id}`.
///
/// Returns the worktree path on success. If the branch name already exists
/// (e.g. a previous run with the same name), the existing branch is checked
/// out rather than creating a new one.
///
/// Runs the (blocking) [`create_worktree_at`] core on a `spawn_blocking`
/// thread: this fn is always awaited from inside `Task::future` on the
/// app's shared tokio runtime, and `git worktree add` does a full working-
/// tree checkout, not the cheap metadata query `repo_from_workspace` does —
/// running it directly on the calling task would tie up a runtime worker
/// thread for that whole checkout.
pub async fn create_worker_worktree(repo: &str, session_id: &str) -> anyhow::Result<String> {
    use anyhow::Context as _;

    let repo = repo.to_string();
    let session_id = session_id.to_string();
    tokio::task::spawn_blocking(move || {
        let worktree_path = std::path::Path::new(&repo)
            .join(".claude")
            .join("worktrees")
            .join(&session_id);
        create_worktree_at(std::path::Path::new(&repo), &worktree_path, &session_id)
    })
    .await
    .context("worktree creation task panicked")?
}

/// Make sure a session's recorded `workspace_path` exists before a Resume
/// or Re-file respawn. Worker worktrees are torn down on completion
/// (`events::remove_worktree_and_artifacts`) and by users pruning
/// `.claude/worktrees/` — but claude-code keys its conversations to the cwd
/// *path string* (`~/.claude/projects/<escaped-path>/<uuid>.jsonl`, which
/// survives the teardown), so recreating the worktree at the exact same
/// path is what makes `--resume` find the conversation again. tmux itself
/// is no safety net: `new-session -c <missing-dir>` exits 0 and silently
/// starts the pane in $HOME (verified on tmux 3.6a), where `--resume` then
/// fails with "No conversation found with session ID".
///
/// - Path exists → nothing to do.
/// - Missing and shaped like a ninox worktree (`{repo}/.claude/worktrees/
///   {session_id}`) → recreate it via [`create_worker_worktree`]. Cleanup
///   deletes the branch along with the worktree, and that's fine: a fresh
///   branch is cut from the repo's HEAD in that case (the conversation
///   lookup only needs the *path* back, not the branch), while a surviving
///   branch is checked out again. Re-seeds the brain skill the original
///   spawn wrote (git-excluded, so never on the branch either way).
/// - Missing and anything else → error, so the spawn fails visibly instead
///   of the agent silently running in the wrong directory.
pub async fn ensure_session_workspace(workspace: &str, session_id: &str) -> anyhow::Result<()> {
    if std::path::Path::new(workspace).is_dir() {
        return Ok(());
    }
    let suffix = format!("/.claude/worktrees/{session_id}");
    let Some(repo_root) = workspace.strip_suffix(&suffix).filter(|r| !r.is_empty()) else {
        anyhow::bail!(
            "workspace {workspace} is gone and is not a ninox worker worktree — cannot recreate it"
        );
    };
    anyhow::ensure!(
        std::path::Path::new(repo_root).is_dir(),
        "workspace {workspace} is gone and its repo root {repo_root} no longer exists"
    );
    create_worker_worktree(repo_root, session_id).await?;
    if let Err(e) = seed_worker_brain_skill(workspace).await {
        tracing::warn!("failed to re-seed brain skill for {session_id}: {e}");
    }
    Ok(())
}

/// Walk up from `start` (inclusive) looking for the nearest ancestor
/// directory containing a `.git` entry — either a real repo's `.git`
/// directory, or a linked worktree's `.git` gitfile. `start` itself need
/// not exist (or even have existing ancestors) since this only ever calls
/// `Path::exists`, which returns `false` rather than erroring for missing
/// paths — used by the Standalone spawn-modal's auto-create path, where
/// the user-typed workspace is by definition missing.
///
/// Returns `None` if no such ancestor is found before the filesystem root.
pub fn find_repo_root(start: &std::path::Path) -> Option<std::path::PathBuf> {
    let mut dir = Some(start);
    while let Some(d) = dir {
        if d.join(".git").exists() {
            return Some(d.to_path_buf());
        }
        dir = d.parent();
    }
    None
}

/// Core `git worktree add` logic shared by [`create_worker_worktree`]
/// (always nests under `{repo}/.claude/worktrees/{session_id}`) and the
/// Standalone spawn-modal's auto-create path (targets the exact user-typed
/// path via [`find_repo_root`]).
///
/// Returns the target path (stringified) on success. If `branch` already
/// exists (e.g. a previous run with the same name), the existing branch is
/// checked out rather than creating a new one. Blocking (not async): called
/// directly from the modal's synchronous confirm handler, which cannot
/// `.await`; mirrors the blocking `git` calls already used elsewhere in
/// this module (e.g. `repo_from_workspace`) even when invoked from async
/// call sites.
pub fn create_worktree_at(
    repo_root: &std::path::Path,
    target: &std::path::Path,
    branch: &str,
) -> anyhow::Result<String> {
    use anyhow::Context as _;
    use std::process::Command;

    let repo_str = repo_root.to_string_lossy().to_string();
    let target_str = target.to_string_lossy().to_string();

    // Attempt 1: create a fresh branch named after `branch`.
    let out = Command::new("git")
        .args(["-C", &repo_str, "worktree", "add", &target_str, "-b", branch])
        .output()
        .context("git worktree add")?;

    if out.status.success() {
        ensure_statusline_settings(target);
        return Ok(target_str);
    }

    // Attempt 2: branch already exists — check it out without -b.
    let stderr = String::from_utf8_lossy(&out.stderr);
    if stderr.contains("already exists") {
        let out2 = Command::new("git")
            .args(["-C", &repo_str, "worktree", "add", &target_str, branch])
            .output()
            .context("git worktree add (existing branch)")?;
        if out2.status.success() {
            ensure_statusline_settings(target);
            return Ok(target_str);
        }
        anyhow::bail!("{}", String::from_utf8_lossy(&out2.stderr).trim());
    }

    anyhow::bail!("{}", stderr.trim());
}

/// Write a minimal `.claude/settings.json` (`statusLine` only) into a
/// freshly created worker worktree, unless one already exists (e.g.
/// checked into the branch). Best-effort: any failure here must never fail
/// worktree creation itself, so errors are swallowed rather than
/// propagated.
fn ensure_statusline_settings(worktree_path: &std::path::Path) {
    let claude_dir = worktree_path.join(".claude");
    let settings_path = claude_dir.join("settings.json");
    if settings_path.exists() {
        return;
    }
    let ninox_bin = ninox_core::config::AppConfig::ninox_bin_dir().join("ninox").display().to_string();
    // Single-quote the binary path (mirroring the PATH-prepend quoting above
    // in `spawn_interactive_session`): the default macOS config dir is
    // `~/Library/Application Support/...`, which contains a space, so an
    // unquoted path here would be split into two argv tokens by the shell
    // that ultimately runs this command and never resolve to the binary.
    let ninox_bin_quoted = format!("'{}'", ninox_bin.replace('\'', "'\\''"));
    let settings = serde_json::json!({
        "statusLine": {
            "type": "command",
            "command": format!("{ninox_bin_quoted} statusline"),
            "refreshInterval": 20
        }
    });
    if std::fs::create_dir_all(&claude_dir).is_ok() {
        if let Ok(body) = serde_json::to_string_pretty(&settings) {
            let _ = std::fs::write(&settings_path, body);
        }
    }
}

const WORKER_BRAIN_SKILL: &str = r#"---
name: brain
description: Read and write Ninox's shared knowledge brain. Use before touching code you haven't seen before, and before finishing your task.
---

# Read and Write the Brain

The brain is Ninox's persistent, shared knowledge store. Your session's
brain is already resolved via `NINOX_BRAIN` — these commands act on it with
no extra configuration.

## Before exploring unfamiliar code

Query first — it blends keyword and semantic matches automatically:

```bash
ninox brain query "<name or concept>"
```

If a relevant entry exists, read it before you start digging through files
yourself. It may save you the exploration entirely.

## Before you finish

Write down anything you discovered that the next session — orchestrator or
worker — would otherwise have to rediscover: where something lives, why
it's built the way it is, a gotcha you hit. Create or update a Markdown
file under the section that fits:

```
repos/          where repositories live, their purpose, entry points
symbols/        where types, functions, and modules are defined
concepts/       domain terminology and mental models
patterns/       conventions and recurring implementation shapes
decisions/      why something was built a certain way (ADRs)
architecture/   how the system is structured — components, data flows
relationships/  how repos, services, and teams connect
errors/         known failure modes and how to resolve them
```

Each file needs YAML frontmatter followed by a Markdown body:

```markdown
---
type: repo
name: my-crate
tags: [auth, core]
repos: [my-crate]
updated: 2026-07-06
---

# my-crate

Entry point: `src/main.rs`
Build: `cargo build`

Facts, not prose. Link related entries with `[[other-entry]]`.
```

Then rebuild the index so the write becomes queryable:

```bash
ninox brain index
```

## The Rule

**Query before touching unfamiliar code. Write down what you found before
you're done.** A stale or empty brain is no better than no brain at all.
"#;

/// Writes a worker-flavored brain skill into `workspace` so a spawned
/// worker/standalone session sees "brain" as a real Claude Code skill from
/// the moment it starts, and makes sure the file can never end up in a
/// commit. Best-effort: any failure here should be logged and swallowed by
/// the caller, not treated as fatal to the spawn (mirrors how
/// `setup_orchestrator_root`'s own failures are handled in `main.rs`).
pub async fn seed_worker_brain_skill(workspace: &str) -> anyhow::Result<()> {
    use anyhow::Context as _;
    use tokio::fs;

    let skill_dir = std::path::Path::new(workspace)
        .join(".claude")
        .join("skills")
        .join("brain");
    let skill_path = skill_dir.join("SKILL.md");

    // Guard against clobbering a copy that somehow already got committed
    // (e.g. a branch created before this exclude mechanism existed, or a
    // manual `git add -f`). Ignoring an already-tracked file is a no-op in
    // git — overwriting it here would silently rewrite committed content
    // that a later `git commit -am` would then happily pick up, exactly
    // what the exclude step below is meant to prevent.
    let tracked = tokio::process::Command::new("git")
        .args(["-C", workspace, "ls-files", "--error-unmatch", ".claude/skills/brain/SKILL.md"])
        .output()
        .await;
    if let Ok(out) = tracked {
        if out.status.success() {
            anyhow::bail!(
                "brain skill file is already tracked in this repo — skipping write to avoid touching committed content"
            );
        }
    }

    fs::create_dir_all(&skill_dir).await.context("create .claude/skills/brain")?;
    fs::write(&skill_path, WORKER_BRAIN_SKILL)
        .await
        .context("write brain SKILL.md")?;

    let out = tokio::process::Command::new("git")
        .args(["-C", workspace, "rev-parse", "--git-common-dir"])
        .output()
        .await
        .context("git rev-parse --git-common-dir")?;
    if !out.status.success() {
        // Not a git repo (or git unavailable) — nothing to protect against
        // a commit; the skill file itself is still written above.
        return Ok(());
    }

    let common_dir_raw = String::from_utf8_lossy(&out.stdout).trim().to_string();
    let common_dir = if std::path::Path::new(&common_dir_raw).is_absolute() {
        std::path::PathBuf::from(&common_dir_raw)
    } else {
        std::path::Path::new(workspace).join(&common_dir_raw)
    };
    let exclude_path = common_dir.join("info").join("exclude");

    const EXCLUDE_LINE: &str = ".claude/skills/brain/";
    let existing = fs::read_to_string(&exclude_path).await.unwrap_or_default();
    if !existing.lines().any(|l| l.trim() == EXCLUDE_LINE) {
        if let Some(parent) = exclude_path.parent() {
            fs::create_dir_all(parent).await.context("create info dir")?;
        }
        // Append-only (never a whole-file read-modify-write): even if two
        // spawns race on the same shared `info/exclude`, the worst case is
        // a harmless duplicate line, never a lost concurrent edit.
        use tokio::io::AsyncWriteExt;
        let mut file = fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&exclude_path)
            .await
            .context("open info/exclude for append")?;
        let mut buf = String::new();
        if !existing.is_empty() && !existing.ends_with('\n') {
            buf.push('\n');
        }
        buf.push_str(EXCLUDE_LINE);
        buf.push('\n');
        file.write_all(buf.as_bytes()).await.context("append info/exclude")?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    /// Minimal real git repo so `git worktree add` has a commit to branch
    /// from — `create_worker_worktree` shells out to real `git`.
    fn init_git_repo() -> std::path::PathBuf {
        let dir = tempdir().unwrap().keep();
        let run = |args: &[&str]| {
            std::process::Command::new("git")
                .args(["-C", dir.to_str().unwrap()])
                .args(args)
                .output()
                .unwrap()
        };
        run(&["init", "-q"]);
        run(&["config", "user.email", "test@example.com"]);
        run(&["config", "user.name", "Test"]);
        std::fs::write(dir.join("README.md"), "x").unwrap();
        run(&["add", "."]);
        run(&["commit", "-q", "-m", "init"]);
        dir
    }

    #[tokio::test]
    async fn create_worker_worktree_writes_statusline_settings() {
        let repo = init_git_repo();
        let worktree = create_worker_worktree(repo.to_str().unwrap(), "test-session-1").await.unwrap();

        let settings_path = std::path::Path::new(&worktree).join(".claude").join("settings.json");
        let settings: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(&settings_path).unwrap(),
        ).unwrap();
        assert_eq!(settings["statusLine"]["type"], "command");
        let command = settings["statusLine"]["command"].as_str().unwrap();
        // The binary path is single-quoted (it may contain spaces, e.g. the
        // default macOS config dir `~/Library/Application Support/...`), so
        // extract the first quoted token rather than splitting on whitespace.
        let bin_path = command
            .strip_prefix('\'')
            .and_then(|rest| rest.split('\'').next())
            .unwrap();
        assert!(bin_path.ends_with("/ninox"), "expected a path to the ninox binary, got: {bin_path}");
        assert!(command.ends_with("statusline"));
    }

    #[tokio::test]
    async fn create_worker_worktree_preserves_existing_settings_json() {
        // Simulate a worktree whose branch already carries a checked-in
        // .claude/settings.json (e.g. from a prior run on the same branch
        // name) by pre-creating it in the repo before the worktree exists —
        // easiest here is to create the worktree once, seed a custom
        // settings.json into it, remove the worktree registration, then
        // re-run create_worker_worktree against the same still-existing
        // branch (the "branch already exists" checkout path).
        //
        // The custom settings.json must be committed to the branch (not
        // merely written to disk): `git worktree remove --force` deletes the
        // entire worktree directory, uncommitted files included, so an
        // uncommitted file would simply vanish along with the worktree and
        // this test would pass for the wrong reason (or fail regardless of
        // whether `ensure_statusline_settings` respects an existing file).
        // Committing it is also the realistic scenario the production
        // docstring describes: "unless one already exists (e.g. checked
        // into the branch)".
        let repo = init_git_repo();
        let first = create_worker_worktree(repo.to_str().unwrap(), "test-session-2").await.unwrap();
        let settings_path = std::path::Path::new(&first).join(".claude").join("settings.json");
        std::fs::write(&settings_path, r#"{"userCustom": true}"#).unwrap();
        std::process::Command::new("git")
            .args(["-C", &first, "add", ".claude/settings.json"])
            .output()
            .unwrap();
        std::process::Command::new("git")
            .args(["-C", &first, "commit", "-q", "-m", "custom settings"])
            .output()
            .unwrap();

        std::process::Command::new("git")
            .args(["-C", repo.to_str().unwrap(), "worktree", "remove", "--force", &first])
            .output()
            .unwrap();

        let second = create_worker_worktree(repo.to_str().unwrap(), "test-session-2").await.unwrap();
        let contents = std::fs::read_to_string(
            std::path::Path::new(&second).join(".claude").join("settings.json"),
        ).unwrap();
        assert_eq!(contents, r#"{"userCustom": true}"#);
    }

    #[tokio::test]
    async fn ensure_session_workspace_recreates_missing_worker_worktree() {
        let repo = init_git_repo();
        let worktree = create_worker_worktree(repo.to_str().unwrap(), "ensure-ws-1").await.unwrap();
        // Simulate post-merge teardown: the worktree dir is gone, the branch
        // (and the claude transcript keyed to this path) survive.
        std::process::Command::new("git")
            .args(["-C", repo.to_str().unwrap(), "worktree", "remove", "--force", &worktree])
            .output()
            .unwrap();
        assert!(!std::path::Path::new(&worktree).exists(), "sanity: worktree removed");

        ensure_session_workspace(&worktree, "ensure-ws-1").await.unwrap();

        assert!(std::path::Path::new(&worktree).is_dir(), "worktree must be recreated at the same path");
        let out = std::process::Command::new("git")
            .args(["-C", &worktree, "branch", "--show-current"])
            .output()
            .unwrap();
        assert_eq!(
            String::from_utf8_lossy(&out.stdout).trim(), "ensure-ws-1",
            "the session's original branch must be checked out again",
        );
    }

    #[tokio::test]
    async fn ensure_session_workspace_recreates_worktree_even_when_the_branch_is_gone() {
        let repo = init_git_repo();
        let worktree = create_worker_worktree(repo.to_str().unwrap(), "ensure-ws-2").await.unwrap();
        // Full cleanup teardown: worktree AND branch both removed. Only the
        // claude transcript (keyed to this path, under ~/.claude/projects/)
        // survives — respawning to see that context must still work.
        std::process::Command::new("git")
            .args(["-C", repo.to_str().unwrap(), "worktree", "remove", "--force", &worktree])
            .output()
            .unwrap();
        std::process::Command::new("git")
            .args(["-C", repo.to_str().unwrap(), "branch", "-D", "ensure-ws-2"])
            .output()
            .unwrap();

        ensure_session_workspace(&worktree, "ensure-ws-2").await.unwrap();

        assert!(std::path::Path::new(&worktree).is_dir(), "worktree must be recreated at the same path");
        let out = std::process::Command::new("git")
            .args(["-C", &worktree, "branch", "--show-current"])
            .output()
            .unwrap();
        assert_eq!(
            String::from_utf8_lossy(&out.stdout).trim(), "ensure-ws-2",
            "a fresh branch is created from HEAD when the original is gone",
        );
    }

    #[tokio::test]
    async fn ensure_session_workspace_is_a_noop_when_the_dir_exists() {
        let dir = tempdir().unwrap().keep();
        ensure_session_workspace(dir.to_str().unwrap(), "whatever").await.unwrap();
        assert!(dir.is_dir());
    }

    #[tokio::test]
    async fn ensure_session_workspace_errors_for_a_missing_non_worktree_path() {
        // A missing dir that is NOT a ninox worktree ({repo}/.claude/
        // worktrees/{session_id}) can't be safely recreated — error out so
        // the spawn fails visibly instead of claude starting in $HOME.
        let result = ensure_session_workspace("/definitely/not/a/real/dir", "sess-x").await;
        assert!(result.is_err());
    }

    #[test]
    fn find_repo_root_walks_up_to_the_nearest_git_ancestor() {
        let repo = init_git_repo();
        let nested = repo.join(".claude").join("worktrees").join("does-not-exist-yet");
        // `nested` itself is never created — find_repo_root must not require
        // the path being resolved to exist, only its ancestors.
        assert_eq!(find_repo_root(&nested), Some(repo.clone()));
    }

    #[test]
    fn find_repo_root_returns_none_with_no_git_ancestor() {
        let dir = tempdir().unwrap().keep();
        assert_eq!(find_repo_root(&dir.join("nested").join("deeper")), None);
    }

    #[test]
    fn find_repo_root_recognizes_a_linked_worktrees_gitfile() {
        let repo = init_git_repo();
        let worktree = repo.join("wt1");
        create_worktree_at(&repo, &worktree, "wt1-branch").unwrap();
        assert!(
            worktree.join(".git").is_file(),
            "sanity: a linked worktree's .git is a gitfile, not a directory"
        );

        let nested = worktree.join("nested").join("deeper");
        assert_eq!(find_repo_root(&nested), Some(worktree.clone()));
    }

    #[test]
    fn create_worktree_at_fails_when_branch_is_checked_out_in_another_worktree() {
        let repo = init_git_repo();
        let first = repo.join("first");
        create_worktree_at(&repo, &first, "dup-branch").unwrap();

        let second = repo.join("second");
        let result = create_worktree_at(&repo, &second, "dup-branch");

        assert!(
            result.is_err(),
            "checking out a branch already active in another worktree must fail, not silently succeed"
        );
        assert!(!second.exists(), "the failed attempt must not leave a half-created worktree dir");
    }

    #[test]
    fn create_worktree_at_creates_exact_target_path_on_new_branch() {
        let repo = init_git_repo();
        let target = repo.join(".claude").join("worktrees").join("feat-new-thing");

        let created = create_worktree_at(&repo, &target, "feat-new-thing").unwrap();

        assert_eq!(created, target.to_string_lossy());
        assert!(target.join(".git").exists());
        let out = std::process::Command::new("git")
            .args(["-C", &created, "branch", "--show-current"])
            .output()
            .unwrap();
        assert_eq!(String::from_utf8_lossy(&out.stdout).trim(), "feat-new-thing");
        // ensure_statusline_settings must still run for this path, same as
        // the create_worker_worktree callers get.
        assert!(target.join(".claude").join("settings.json").exists());
    }

    #[test]
    fn create_worktree_at_checks_out_existing_branch_when_it_already_exists() {
        let repo = init_git_repo();
        let target = repo.join(".claude").join("worktrees").join("feat-existing");

        let first = create_worktree_at(&repo, &target, "feat-existing").unwrap();
        std::process::Command::new("git")
            .args(["-C", &repo.to_string_lossy(), "worktree", "remove", "--force", &first])
            .output()
            .unwrap();
        assert!(!target.exists(), "sanity: worktree dir removed but branch remains");

        let second = create_worktree_at(&repo, &target, "feat-existing").unwrap();

        assert_eq!(second, target.to_string_lossy());
        let out = std::process::Command::new("git")
            .args(["-C", &second, "branch", "--show-current"])
            .output()
            .unwrap();
        assert_eq!(String::from_utf8_lossy(&out.stdout).trim(), "feat-existing");
    }

    #[test]
    fn expand_tilde_leaves_absolute_paths_alone() {
        assert_eq!(expand_tilde("/tmp/foo"), "/tmp/foo");
        assert_eq!(expand_tilde("relative/path"), "relative/path");
    }

    #[test]
    fn expand_tilde_expands_home_prefix() {
        let home = dirs::home_dir().expect("home dir").to_string_lossy().to_string();
        assert_eq!(expand_tilde("~"), home);
        assert_eq!(expand_tilde("~/proj"), format!("{home}/proj"));
        // A bare "~user" form is not supported — passed through untouched.
        assert_eq!(expand_tilde("~other/proj"), "~other/proj");
    }

    /// Regression test for the gap where app-spawned sessions (both
    /// Orchestrator and Standalone kinds) never set `NINOX_SESSION`/
    /// `NINOX_DATA_DIR`, unlike the CLI worker path (`main.rs::run_spawn`,
    /// see `worker_env_vars` there). Without these, the gh/git wrapper
    /// scripts can't record PR/branch metadata and the usage poller can't
    /// attribute a workspace's cost/token ingestion back to a session id.
    #[test]
    fn interactive_env_vars_includes_session_attribution() {
        let extra = vec![("NINOX_ORCHESTRATOR_ID".to_string(), "orch-1".to_string())];
        let env = interactive_env_vars(
            "/usr/local/bin/ninox", "/cfg/config.toml", "/brain", "sess-1", "/data/sessions", &extra,
        );
        assert!(env.contains(&("NINOX_SESSION", "sess-1")));
        assert!(env.contains(&("NINOX_DATA_DIR", "/data/sessions")));
        // The legacy ATHENE_* transition names are gone.
        assert!(!env.iter().any(|(k, _)| k.starts_with("ATHENE_")));
        assert!(env.contains(&("NINOX_ORCHESTRATOR_ID", "orch-1")));
    }

    #[tokio::test]
    async fn spawn_persists_claude_session_id() {
        use ninox_core::{config::AgentConfig, store::Store, SessionStatus};
        use tempfile::tempdir;

        let store = std::sync::Arc::new(Store::open(tempdir().unwrap().keep().join("t.db")).unwrap());
        let engine = ninox_core::events::Engine::new(store.clone());
        let ws = tempdir().unwrap().keep().to_string_lossy().to_string();

        let attach = spawn_interactive_session(
            engine,
            InteractiveSpawnParams {
                session_id:        "spawn-uuid-test".into(),
                name:              "spawn-uuid-test".into(),
                workspace:         ws,
                repo:              String::new(),
                orchestrator_id:   None,
                agent:             AgentConfig::default(),
                base_cmd:          "sleep 30".into(),
                catalogue_path:    String::new(),
                extra_env:         Vec::new(),
                started_at:        0,
                claude_session_id: "fixed-uuid-for-test".into(),
                failure_status:    SessionStatus::Terminated,
                summary:           None,
            },
        )
        .await;
        assert!(attach.is_some(), "tmux create must succeed");

        let session = store.get_session("spawn-uuid-test").unwrap().unwrap();
        assert_eq!(session.claude_session_id.as_deref(), Some("fixed-uuid-for-test"));

        ninox_core::tmux::kill_session("spawn-uuid-test").await.ok();
    }

    #[tokio::test]
    async fn spawn_failure_uses_the_caller_supplied_failure_status() {
        use ninox_core::{config::AgentConfig, store::Store, tmux, types::Session, SessionStatus};
        use tempfile::tempdir;

        let store = std::sync::Arc::new(Store::open(tempdir().unwrap().keep().join("t.db")).unwrap());
        let engine = ninox_core::events::Engine::new(store.clone());
        // Pre-insert the row exactly like the app's optimistic-insert-then-spawn
        // flow does, so the failure branch's `get_session`+update has a row to find.
        store.upsert_session(&Session {
            id: "spawn-fail-test".into(), orchestrator_id: None, name: "n".into(),
            repo: String::new(), status: SessionStatus::Working, agent_type: "claude-code".into(),
            cost_usd: 0.0, started_at: 0, pr_number: None, pr_id: None,
            workspace_path: None, pid: None, model: None, context_tokens: None,
            catalogue_path: None,
            context_used_pct: None, context_total_tokens: None, context_window_size: None,
            claude_session_id: Some("fixed-uuid".into()),
            summary: None,
            terminal_at: None,
        }).unwrap();

        let ws = tempdir().unwrap().keep().to_string_lossy().to_string();

        // Deviation from the brief's literal test body: a nonexistent `-c`
        // workspace does NOT make `tmux new-session` fail synchronously on
        // every tmux build (verified: tmux 3.6a here returns exit 0 and only
        // the spawned shell dies asynchronously afterward). A pre-existing
        // LIVE session under the same id is a build-independent way to force
        // `tmux::create_session` to fail deterministically ("duplicate
        // session" — see its own doc comment), which is all this test needs:
        // any `create_session` failure must route through `p.failure_status`.
        tmux::create_session("spawn-fail-test", &ws, "sleep 30", &[]).await.unwrap();

        let attach = spawn_interactive_session(
            engine,
            InteractiveSpawnParams {
                session_id:        "spawn-fail-test".into(),
                name:              "n".into(),
                workspace:         ws,
                repo:              String::new(),
                orchestrator_id:   None,
                agent:             AgentConfig::default(),
                base_cmd:          "sleep 30".into(),
                catalogue_path:    String::new(),
                extra_env:         Vec::new(),
                started_at:        0,
                claude_session_id: "fixed-uuid".into(),
                failure_status:    SessionStatus::Interrupted,
                summary:           None,
            },
        )
        .await;
        assert!(attach.is_none(), "tmux create must fail for a duplicate session id");

        tmux::kill_session("spawn-fail-test").await.ok();

        let session = store.get_session("spawn-fail-test").unwrap().unwrap();
        assert!(
            matches!(session.status, SessionStatus::Interrupted),
            "failure_status must be honored, not hardcoded to Terminated",
        );
    }

    #[tokio::test]
    async fn seed_worker_brain_skill_writes_skill_with_frontmatter() {
        use tempfile::tempdir;
        let dir = tempdir().unwrap();
        let ws = dir.path().to_str().unwrap().to_string();
        tokio::process::Command::new("git")
            .args(["init", "-q", &ws])
            .status()
            .await
            .unwrap();

        seed_worker_brain_skill(&ws).await.unwrap();

        let skill = tokio::fs::read_to_string(
            dir.path().join(".claude").join("skills").join("brain").join("SKILL.md"),
        )
        .await
        .unwrap();
        assert!(skill.starts_with("---\n"), "skill must start with YAML frontmatter");
        assert!(skill.contains("name: brain"));
        assert!(skill.contains("description:"));
        assert!(skill.contains("ninox brain query"));
    }

    #[tokio::test]
    async fn seed_worker_brain_skill_excludes_itself_from_git_idempotently() {
        use tempfile::tempdir;
        let dir = tempdir().unwrap();
        let ws = dir.path().to_str().unwrap().to_string();
        tokio::process::Command::new("git")
            .args(["init", "-q", &ws])
            .status()
            .await
            .unwrap();

        seed_worker_brain_skill(&ws).await.unwrap();
        seed_worker_brain_skill(&ws).await.unwrap();

        let exclude = tokio::fs::read_to_string(dir.path().join(".git").join("info").join("exclude"))
            .await
            .unwrap();
        let count = exclude.lines().filter(|l| l.trim() == ".claude/skills/brain/").count();
        assert_eq!(count, 1, "the exclude line must appear exactly once, not duplicated");

        // The whole point of the exclude: the skill file must never show up
        // as untracked/stageable in this repo.
        let status = tokio::process::Command::new("git")
            .args(["-C", &ws, "status", "--porcelain"])
            .output()
            .await
            .unwrap();
        assert!(
            String::from_utf8_lossy(&status.stdout).trim().is_empty(),
            "the brain skill file must be excluded from git status, not merely present on disk"
        );
    }

    #[tokio::test]
    async fn seed_worker_brain_skill_skips_exclude_when_not_a_git_repo() {
        use tempfile::tempdir;
        let dir = tempdir().unwrap();
        let ws = dir.path().to_str().unwrap().to_string();

        seed_worker_brain_skill(&ws).await.unwrap();

        assert!(
            dir.path().join(".claude").join("skills").join("brain").join("SKILL.md").exists(),
            "skill file must still be written even outside a git repo"
        );
        assert!(!dir.path().join(".git").exists(), "test setup sanity check: no git repo here");
    }

    #[tokio::test]
    async fn seed_worker_brain_skill_refuses_to_overwrite_a_tracked_copy() {
        use tempfile::tempdir;
        let dir = tempdir().unwrap();
        let ws = dir.path().to_str().unwrap().to_string();
        tokio::process::Command::new("git").args(["init", "-q", &ws]).status().await.unwrap();

        // Simulate a pre-existing tracked copy, e.g. committed before this
        // exclude mechanism existed.
        let skill_dir = dir.path().join(".claude").join("skills").join("brain");
        tokio::fs::create_dir_all(&skill_dir).await.unwrap();
        tokio::fs::write(skill_dir.join("SKILL.md"), "tracked content\n").await.unwrap();
        tokio::process::Command::new("git")
            .args(["-C", &ws, "add", ".claude/skills/brain/SKILL.md"])
            .status()
            .await
            .unwrap();
        let commit_status = tokio::process::Command::new("git")
            .args([
                "-C", &ws,
                "-c", "user.email=test@example.com",
                "-c", "user.name=Test",
                "commit", "-q", "-m", "tracked",
            ])
            .status()
            .await
            .unwrap();
        assert!(commit_status.success(), "git commit must succeed to simulate a tracked copy");

        let result = seed_worker_brain_skill(&ws).await;
        assert!(result.is_err(), "must refuse to silently overwrite a tracked copy");

        let content = tokio::fs::read_to_string(skill_dir.join("SKILL.md")).await.unwrap();
        assert_eq!(content, "tracked content\n", "tracked content must be left untouched");
    }

    #[tokio::test]
    async fn seed_worker_brain_skill_targets_shared_common_dir_from_a_worktree() {
        use tempfile::tempdir;
        let repo_dir = tempdir().unwrap();
        let repo = repo_dir.path().to_str().unwrap().to_string();
        tokio::process::Command::new("git").args(["init", "-q", &repo]).status().await.unwrap();
        // `-c user.email=`/`-c user.name=` — a bare `git commit` fails with
        // "Please tell me who you are" on any machine/CI runner with no
        // global git identity configured. That failure was previously
        // silent here (`.status()` only checks the command actually ran,
        // not that it exited 0), so the commit silently no-opped, `git
        // worktree add -b` below then had no commit to branch from and
        // fell back to an orphan branch, and the test failed later with a
        // confusing, unrelated-looking assertion on the exclude file
        // instead of a clear "commit failed" error. `.success()` below
        // makes that failure mode loud instead of silent.
        let commit_status = tokio::process::Command::new("git")
            .args([
                "-C", &repo,
                "-c", "user.email=test@example.com",
                "-c", "user.name=Test",
                "commit", "-q", "-m", "init", "--allow-empty",
            ])
            .status()
            .await
            .unwrap();
        assert!(commit_status.success(), "git commit must succeed to give the worktree a branch point");

        let worktree_path = repo_dir.path().join("wt");
        let worktree = worktree_path.to_str().unwrap().to_string();
        tokio::process::Command::new("git")
            .args(["-C", &repo, "worktree", "add", &worktree, "-b", "wt-branch"])
            .status()
            .await
            .unwrap();

        seed_worker_brain_skill(&worktree).await.unwrap();

        // The exclude must land in the MAIN repo's shared .git/info/exclude,
        // not anywhere under the linked worktree's own (file-based) .git.
        let exclude = tokio::fs::read_to_string(
            repo_dir.path().join(".git").join("info").join("exclude"),
        )
        .await
        .unwrap();
        assert!(exclude.lines().any(|l| l.trim() == ".claude/skills/brain/"));

        assert!(
            worktree_path.join(".claude").join("skills").join("brain").join("SKILL.md").exists(),
            "skill file must be written into the worktree itself"
        );
    }
}

#[cfg(test)]
mod persistence_probe {
    use super::*;
    use ninox_core::{config::AgentConfig, store::Store};
    use std::sync::Arc;
    use tempfile::tempdir;

    /// End-to-end persistence probe — NOT part of the suite (`--ignored`).
    /// Spawns a REAL interactive agent session through the exact app code
    /// path, attaches+drops a client like the app quitting, then this test
    /// process exits. The controller verifies from outside that the tmux
    /// session survives. Cleanup is the controller's job (kill-session).
    #[tokio::test]
    #[ignore]
    async fn spawn_probe() {
        let store = Arc::new(Store::open(tempdir().unwrap().keep().join("p.db")).unwrap());
        let engine = ninox_core::events::Engine::new(store);
        let ws = tempdir().unwrap().keep().to_string_lossy().to_string();

        let attach = spawn_interactive_session(
            engine.clone(),
            InteractiveSpawnParams {
                session_id:      "fnd-probe".into(),
                name:            "fnd-probe".into(),
                workspace:       ws,
                repo:            String::new(),
                orchestrator_id: None,
                agent:           AgentConfig::default(),
                base_cmd:        ninox_core::config::AppConfig::default()
                                     .registry()
                                     .interactive_cmd(&AgentConfig::default(), "probe-fixed-id"),
                catalogue_path:  String::new(),
                extra_env:       Vec::new(),
                started_at:      0,
                claude_session_id: "probe-fixed-id".into(),
                failure_status:  ninox_core::SessionStatus::Terminated,
                summary:           None,
            },
        )
        .await;
        let argv = attach.expect("tmux create must succeed");

        // Mirror the app: attach a hidden client, then drop it (Cmd-Q path).
        let client = ninox_core::client::AttachedClient::spawn(
            engine, "fnd-probe".into(), argv, 140, 40, 0,
        )
        .expect("attach");
        tokio::time::sleep(std::time::Duration::from_secs(4)).await;
        drop(client);
        tokio::time::sleep(std::time::Duration::from_millis(500)).await;
        // test process exits here — the "app" is gone.
    }

    /// End-to-end proof that the cost/context tracking fix works against a
    /// REAL `claude` session, driven exactly the way the app drives one:
    /// spawn via `spawn_interactive_session` (the code path that used to be
    /// missing `NINOX_SESSION`/`NINOX_DATA_DIR`), send one cheap prompt,
    /// then assert the usage poller's ingestion (`ninox_core::lifecycle::
    /// usage::ingest_usage_for_workspace`) picks up a non-zero cost and
    /// context-token count from the real `~/.claude/projects/...` transcript
    /// `claude` itself writes. NOT part of the suite (`--ignored`) — costs a
    /// small amount of real API usage and needs the `claude` CLI installed.
    #[tokio::test]
    #[ignore]
    async fn usage_ingestion_probe() {
        let store = Arc::new(Store::open(tempdir().unwrap().keep().join("p.db")).unwrap());
        let engine = ninox_core::events::Engine::new(store.clone());
        let ws = tempdir().unwrap().keep().to_string_lossy().to_string();
        let sid = "fnd-usage-probe".to_string();

        let attach = spawn_interactive_session(
            engine.clone(),
            InteractiveSpawnParams {
                session_id:      sid.clone(),
                name:            sid.clone(),
                workspace:       ws.clone(),
                repo:            String::new(),
                orchestrator_id: None,
                agent:           AgentConfig::default(),
                base_cmd:        ninox_core::config::AppConfig::default()
                                     .registry()
                                     .interactive_cmd(&AgentConfig::default(), "probe-fixed-id"),
                catalogue_path:  String::new(),
                extra_env:       Vec::new(),
                started_at:      0,
                claude_session_id: "probe-fixed-id".into(),
                failure_status:  ninox_core::SessionStatus::Terminated,
                summary:           None,
            },
        )
        .await;
        let argv = attach.expect("tmux create must succeed");
        let client = ninox_core::client::AttachedClient::spawn(
            engine.clone(), sid.clone(), argv, 140, 40, 0,
        )
        .expect("attach");

        // Give the TUI a moment to finish booting before sending input — the
        // welcome screen + MCP-auth check can take a while under load, and
        // input sent too early is silently dropped.
        tokio::time::sleep(std::time::Duration::from_secs(15)).await;
        engine
            .send_to_session(&sid, "Reply with exactly one word: OK")
            .await
            .expect("send prompt");

        // Poll until the transcript shows up with non-zero usage, or time out.
        let mut snapshot = None;
        for _ in 0..40 {
            tokio::time::sleep(std::time::Duration::from_secs(2)).await;
            if let Some(s) = ninox_core::lifecycle::usage::ingest_usage_for_workspace(&ws) {
                snapshot = Some(s);
                break;
            }
        }

        drop(client);

        let snapshot = snapshot.expect("usage should be ingested from the real claude transcript");
        assert!(snapshot.cost_usd > 0.0, "cost_usd must be non-zero once claude has taken a turn");
        assert!(snapshot.context_tokens > 0, "context_tokens must be non-zero once claude has taken a turn");
    }
}
